const products = [
  // ================= ELECTRONICS =================
  {
    name: "Apple iPhone 14",
    description: "Apple smartphone with A15 Bionic chip",
    price: 79900,
    image: "https://m.media-amazon.com/images/I/61cwywLZR-L._SL1500_.jpg",
    category: "Electronics",
    stock: 25,
  },
  {
    name: "Samsung Galaxy S23",
    description: "Flagship smartphone with Snapdragon 8 Gen 2",
    price: 74999,
    image: "https://m.media-amazon.com/images/I/61RZDb2mQxL._SL1500_.jpg",
    category: "Electronics",
    stock: 30,
  },
  {
    name: "Sony WH-1000XM5",
    description: "Noise-cancelling Bluetooth headphones",
    price: 29990,
    image: "https://m.media-amazon.com/images/I/51SKmu2yJXL._SL1500_.jpg",
    category: "Electronics",
    stock: 40,
  },
  {
    name: "Apple MacBook Air M2",
    description: "13.6-inch laptop with M2 chip",
    price: 109900,
    image: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg",
    category: "Electronics",
    stock: 10,
  },
  {
    name: "Dell Inspiron 15",
    description: "15.6-inch FHD laptop with Intel i5",
    price: 56990,
    image: "https://m.media-amazon.com/images/I/71F4jU7MR1L._SL1500_.jpg",
    category: "Electronics",
    stock: 15,
  },
  {
    name: "Logitech MX Master 3S",
    description: "Ergonomic wireless mouse",
    price: 9995,
    image: "https://m.media-amazon.com/images/I/61ni3t1ryQL._SL1500_.jpg",
    category: "Electronics",
    stock: 50,
  },
  {
    name: "Apple Watch Series 9",
    description: "Fitness smartwatch with OLED display",
    price: 41999,
    image: "https://m.media-amazon.com/images/I/71qb9P9Zc3L._SL1500_.jpg",
    category: "Electronics",
    stock: 20,
  },
  {
    name: "Samsung 55-inch 4K TV",
    description: "Smart LED TV with HDR10",
    price: 52999,
    image: "https://m.media-amazon.com/images/I/71kr3WAj1FL._SL1500_.jpg",
    category: "Electronics",
    stock: 12,
  },
  {
    name: "JBL Flip 6 Speaker",
    description: "Portable waterproof Bluetooth speaker",
    price: 11999,
    image: "https://m.media-amazon.com/images/I/71TL3gov0yL._SL1500_.jpg",
    category: "Electronics",
    stock: 35,
  },
  {
    name: "Canon EOS 1500D",
    description: "DSLR Camera with 18-55mm lens",
    price: 38999,
    image: "https://m.media-amazon.com/images/I/914hFeTU2-L._SL1500_.jpg",
    category: "Electronics",
    stock: 8,
  },

  // ================= FASHION =================
  {
    name: "Nike Air Max 270",
    description: "Stylish running shoes",
    price: 9995,
    image: "https://m.media-amazon.com/images/I/71LT6BDoDLL._SL1500_.jpg",
    category: "Fashion",
    stock: 45,
  },
  {
    name: "Adidas Men's Hoodie",
    description: "Comfortable cotton hoodie",
    price: 3499,
    image: "https://m.media-amazon.com/images/I/71R7YQ2N1-L._SL1500_.jpg",
    category: "Fashion",
    stock: 60,
  },
  {
    name: "Levi's 511 Slim Jeans",
    description: "Classic slim-fit jeans",
    price: 2499,
    image: "https://m.media-amazon.com/images/I/81W7pZQh0hL._SL1500_.jpg",
    category: "Fashion",
    stock: 80,
  },
  {
    name: "Fossil Chronograph Watch",
    description: "Men’s stainless steel watch",
    price: 8995,
    image: "https://m.media-amazon.com/images/I/81vwZEB96cL._SL1500_.jpg",
    category: "Fashion",
    stock: 33,
  },
  {
    name: "Puma Backpack",
    description: "Durable sports backpack",
    price: 1499,
    image: "https://m.media-amazon.com/images/I/71A4RmhG6DL._SL1500_.jpg",
    category: "Fashion",
    stock: 55,
  },

  // ================= HOME & KITCHEN =================
  {
    name: "Prestige Pressure Cooker",
    description: "Aluminium cooker 5L",
    price: 1999,
    image: "https://m.media-amazon.com/images/I/61Z0rGUNShL._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 70,
  },
  {
    name: "Bajaj 750W Mixer Grinder",
    description: "3-jar mixer grinder",
    price: 3299,
    image: "https://m.media-amazon.com/images/I/71kCz24HGcL._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 20,
  },
  {
    name: "Philips Air Fryer",
    description: "Rapid Air technology fryer",
    price: 8999,
    image: "https://m.media-amazon.com/images/I/71xJ2yqCC2L._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 15,
  },
  {
    name: "Milton Thermosteel Bottle",
    description: "1000ml stainless steel bottle",
    price: 799,
    image: "https://m.media-amazon.com/images/I/71Z8bQmUWCL._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 120,
  },
  {
    name: "Sleepwell Memory Foam Pillow",
    description: "Comfortable soft memory foam pillow",
    price: 1499,
    image: "https://m.media-amazon.com/images/I/81G9vDOMk1L._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 45,
  },

  // ================= BEAUTY & PERSONAL CARE =================
  {
    name: "Nivea Body Lotion",
    description: "Deep moisturising lotion",
    price: 349,
    image: "https://m.media-amazon.com/images/I/61rVb4YvTeL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 100,
  },
  {
    name: "Beardo Beard Oil",
    description: "Beard growth and nourishment oil",
    price: 299,
    image: "https://m.media-amazon.com/images/I/61z0AW-QNDL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 90,
  },
  {
    name: "Mamaearth Face Wash",
    description: "Tea tree oil acne face wash",
    price: 249,
    image: "https://m.media-amazon.com/images/I/61-HKjtVbTL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 110,
  },
  {
    name: "L’Oréal Shampoo",
    description: "Anti-hair fall shampoo",
    price: 399,
    image: "https://m.media-amazon.com/images/I/61NsyTo3BzL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 85,
  },
  {
    name: "Philips Hair Dryer",
    description: "1200W quick-dry hair dryer",
    price: 1299,
    image: "https://m.media-amazon.com/images/I/61yqN8nc9fL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 38,
  },

  // ================= SPORTS & OUTDOORS =================
  {
    name: "Yonex Badminton Racket",
    description: "Lightweight graphite racket",
    price: 2199,
    image: "https://m.media-amazon.com/images/I/71-lP8DZ4aL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 50,
  },
  {
    name: "Cosco Football",
    description: "Size 5 football for beginners",
    price: 799,
    image: "https://m.media-amazon.com/images/I/71CtK5vC9GL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 75,
  },
  {
    name: "Puma Gym Gloves",
    description: "Workout gloves for men",
    price: 699,
    image: "https://m.media-amazon.com/images/I/81N9f7oO7NL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 60,
  },
  {
    name: "Nike Sports Water Bottle",
    description: "Leak-proof BPA-free bottle",
    price: 899,
    image: "https://m.media-amazon.com/images/I/71pQ8KM2SOI._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 100,
  },
  {
    name: "Adidas Duffle Gym Bag",
    description: "Spacious training duffle bag",
    price: 2499,
    image: "https://m.media-amazon.com/images/I/81lyTB9YhPL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 30,
  },

  // ------------ Add 25 More to Reach Total 50 (Continuing Below) ------------
  
  {
    name: "HP Wireless Keyboard",
    description: "Slim wireless keyboard",
    price: 1199,
    image: "https://m.media-amazon.com/images/I/71bqJb5R2ML._SL1500_.jpg",
    category: "Electronics",
    stock: 70,
  },
  {
    name: "Realme Buds Wireless 3",
    description: "Neckband with ANC",
    price: 1799,
    image: "https://m.media-amazon.com/images/I/71rlY+Zl4YL._SL1500_.jpg",
    category: "Electronics",
    stock: 80,
  },
  {
    name: "Boat Airdopes 141",
    description: "True wireless earbuds",
    price: 1299,
    image: "https://m.media-amazon.com/images/I/61KNJav3S9L._SL1500_.jpg",
    category: "Electronics",
    stock: 90,
  },
  {
    name: "Samsung 1TB SSD",
    description: "Portable solid state drive",
    price: 8499,
    image: "https://m.media-amazon.com/images/I/61wLJL3V3JL._SL1500_.jpg",
    category: "Electronics",
    stock: 40,
  },
  {
    name: "Tenda WiFi Router",
    description: "High-speed dual-band router",
    price: 1499,
    image: "https://m.media-amazon.com/images/I/71q5kJc4WsL._SL1500_.jpg",
    category: "Electronics",
    stock: 55,
  },

  {
    name: "Wooden Study Table",
    description: "Compact study desk",
    price: 4999,
    image: "https://m.media-amazon.com/images/I/71vPxNcNGBL._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 14,
  },
  {
    name: "Havells LED Bulb (Pack of 3)",
    description: "9W B22 LED bulbs",
    price: 299,
    image: "https://m.media-amazon.com/images/I/61BPdZiZp0L._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 200,
  },
  {
    name: "Non-Stick Frying Pan",
    description: "Induction-friendly non-stick pan",
    price: 899,
    image: "https://m.media-amazon.com/images/I/71FVKyYVJHL._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 50,
  },
  {
    name: "Handmade Cotton Bedsheet",
    description: "Queen-size bedsheet with 2 pillow covers",
    price: 999,
    image: "https://m.media-amazon.com/images/I/81vP2CgLK6L._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 45,
  },
  {
    name: "Electric Kettle 1.5L",
    description: "Automatic shutoff kettle",
    price: 699,
    image: "https://m.media-amazon.com/images/I/61mQYapQrfL._SL1500_.jpg",
    category: "Home & Kitchen",
    stock: 60,
  },

  {
    name: "Gillette Razor",
    description: "Men's shaving razor",
    price: 199,
    image: "https://m.media-amazon.com/images/I/71d-DVYIb2L._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 150,
  },
  {
    name: "Vaseline Lip Balm",
    description: "Moisturising lip care",
    price: 89,
    image: "https://m.media-amazon.com/images/I/61wcIvkFmSL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 300,
  },
  {
    name: "Lakme Compact Powder",
    description: "Long-lasting matte finish",
    price: 299,
    image: "https://m.media-amazon.com/images/I/71MwTx9cXxL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 85,
  },
  {
    name: "Philips Trimmer",
    description: "Adjustable beard trimmer",
    price: 1299,
    image: "https://m.media-amazon.com/images/I/71ULP1BAShL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 75,
  },
  {
    name: "Tresemme Conditioner",
    description: "Smooth and shine conditioner",
    price: 399,
    image: "https://m.media-amazon.com/images/I/71tq5Wp1FEL._SL1500_.jpg",
    category: "Beauty & Personal Care",
    stock: 90,
  },

  {
    name: "Nivia Running Shoes",
    description: "Breathable sports shoes",
    price: 1599,
    image: "https://m.media-amazon.com/images/I/71k2TiFqYbL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 70,
  },
  {
    name: "Wildcraft Trekking Bag",
    description: "45L hiking backpack",
    price: 3499,
    image: "https://m.media-amazon.com/images/I/71LURQpXbdL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 26,
  },
  {
    name: "Strauss Yoga Mat",
    description: "6mm non-slip yoga mat",
    price: 799,
    image: "https://m.media-amazon.com/images/I/71VvUFLAIpL._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 90,
  },
  {
    name: "Cosco Cricket Bat",
    description: "Full-size Kashmir willow bat",
    price: 1299,
    image: "https://m.media-amazon.com/images/I/81hjGZEgHML._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 55,
  },
  {
    name: "Spalding Basketball",
    description: "Outdoor basketball",
    price: 1399,
    image: "https://m.media-amazon.com/images/I/71Kft2oig4L._SL1500_.jpg",
    category: "Sports & Outdoors",
    stock: 48,
  }
];


export default products;